# Generated by Django 3.1.7 on 2021-03-10 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event name')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('user', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='User')),
                ('info', models.JSONField(verbose_name='JSON Info')),
                ('timestamp', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventtype')),
            ],
        ),
    ]
